---
kind: pipeline
type: docker
name: lint
steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-alpine
    pull: if-not-exists
    commands:
      - hadolint --version
      - hadolint Dockerfile*

---

kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: latest  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/hddtemp-docker
    compress: true
    purge: true
    cache_from: "modem7/hddtemp-docker:latest"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v7
      - linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]


trigger:
  event:
    - cron
  cron:
    - hddtemp_latest

---

kind: pipeline
type: docker
name: monthly

platform:
  os: linux
  arch: amd64

steps:
- name: monthly  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/hddtemp-docker
    purge: true
    cache_from: "modem7/hddtemp-docker:monthly"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v7
      - linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: monthly

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
  - cron
  cron:
  - hddtemp_monthly

---

kind: pipeline
type: docker
name: stable

platform:
  os: linux
  arch: amd64

steps:
- name: stable  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/hddtemp-docker
    purge: true
    cache_from: "modem7/hddtemp-docker:stable"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v7
      - linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: stable

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
  - cron
  cron:
  - hddtemp_stable

---

kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/hddtemp-docker
    purge: true
    compress: true
    use_cache: true
    cache_from: "modem7/hddtemp-docker:test"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v7
      - linux/arm64/v8
    dockerfile: test/Dockerfile
    context: test/
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: test

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
    - custom