kind: pipeline
type: docker
name: latest 

steps:
- name: latest
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
    repo: modem7/hddtemp-docker
    tags: 
      - latest 
      - 1.4

# trigger:
  # event:
  # - cron
  # cron:
  # - hastebin_latest

---

kind: pipeline
type: docker
name: stable 

steps:
- name: stable
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
    repo: modem7/hddtemp-docker
    tags: stable

# trigger:
  # event:
  # - cron
  # cron:
  # - hastebin_latest