---

kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: latest  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/hddtemp-docker
    purge: true
    compress: true
    no_cache: false
    build_args: BUILDKIT_INLINE_CACHE=1
    cache_from: "modem7/hddtemp-docker:latest"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - 0.4.3.2

- name: pushrm-dockerhub
  image: chko/docker-pushrm
  environment:
    DOCKER_USER:
      from_secret: docker_username
    DOCKER_PASS:
      from_secret: docker_password
    PUSHRM_FILE: README.md
    PUSHRM_SHORT: Docker container for hddtemp - http://savannah.nongnu.org/projects/hddtemp
    PUSHRM_TARGET: modem7/hddtemp-docker
  when:
    status:
      - success

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
    - custom