name: Dependencies
on:
  schedule:
  - cron: "30 2 * * *"
  workflow_dispatch:
jobs:
  updates:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Update dependencies
      working-directory: scripts
      run: |
        sudo apt-get update
        sh update_dependencies.sh

    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "chore(deps): update dependencies.json"
        branch: features/update-dependencies
        title: Update APT packages
        body: Updated dependencies.json
        delete-branch: true
        labels: dependencies
        reviewers: modem7
